### ISSUE TITLE
IntelliSense after typeing symbol (like comma, semicolon)

### ISSUE THREAD

**Issue by sinpen** [austin-----/code-gnu-global#21] opened 2016-07-10 04:47 UTC
When I finished one line with a ";" in the end and I want to type "enter" to the next line, it always IntelliSenses me an "a".  I don't want this feature.

**Comment by austin-----** [comment] 2016-07-12 04:03
I could not reproduce this behavior. Could you please share your OS, VSC version? Does this always happen? Thanks.

**Comment by sinpen** [comment] 2016-07-12 06:03
OK, thanks for your reply. My OS is windows 10, and VSC version is 1.3.0. Maybe it is not a clear i described. 
It intellisenses me something and pitches on the first one by default after ';' sometimes. And when i finished the "#include <something>" and type enter, it  will show me something like the image below. i want to use "enter" to jump to next line but it takes the "fstream" into the line. ( I am very sorry to my poor English making the description too confused.) Thanks.
![image](https://cloud.githubusercontent.com/assets/9527221/16756492/11599826-4838-11e6-9db5-fe207f0f5a3c.png)

**Comment by robin-kuester** [comment] 2016-07-24 16:49
I have the same issue.

**Comment by sinpen** [comment] 2016-07-28 08:42
Sorry. Maybe it is not caused by "c++ intellisense".  And the "C/C++" extension made by Microsoft may has something mistake. I uninstall the extension "c++ intellisense", but the problem also exists.

**Comment by austin-----** [comment] 2016-08-03 04:12
Thanks for reporting back @sinpen . I will thus close this issue.

**Closed by austin-----** 2016-08-03 04:12 UTC
